backend:
  name: github
  repo: ssstew368-coder/LePetitJuriste
  branch: main
  auth_type: implicit   # ou pkce si tu veux plus sécurisé
  base_url: https://github.com
  auth_endpoint: login/oauth/authorize
  token_endpoint: login/oauth/access_token
  api_root: https://api.github.com
  squash_merges: true

media_folder: "images"
public_folder: "/images"

collections:
  - name: "livres"
    label: "Livres"
    folder: "data/livres"
    create: true
    slug: "{{titre}}"
    extension: "json"
    format: "json"
    fields:
      - {label: "Catégorie", name: "categorie", widget: "string", required: true}
      - {label: "Titre", name: "titre", widget: "string", required: true}
      - {label: "Auteur", name: "auteur", widget: "string", default: "Steven"}
      - {label: "Prix", name: "prix", widget: "string", required: true}
      - {label: "Description courte", name: "desc_courte", widget: "text"}
      - {label: "Description longue", name: "desc_longue", widget: "markdown"}
      - {label: "Image couverture", name: "image", widget: "image", required: true}
      - {label: "Extraits (images)", name: "extraits", widget: "list", field: {label: "Image", name: "image", widget: "image"}}
